practice gihub scretects

diff --git a/.github/workflows/manual.yml b/.github/workflows/manual.yml
--- a/.github/workflows/manual.yml
+++ b/.github/workflows/manual.yml
@@ -7,6 +7,7 @@ on:
   pull_request:
 
   workflow_dispatch:
+
 env:
   APP_NAME: "Python CI Practice"
 
@@ -14,9 +15,7 @@ jobs:
   test:
     runs-on: ubuntu-latest
 
-    steps:
-      - name: Test
-        run: echo "Testing..."
+    
 
       - name: Success message
         if: success()
@@ -29,3 +28,18 @@ jobs:
     steps:
       - name: Check Python
         run: python --version
+
+        steps:
+      - name: Test
+        run: echo "Testing..."
+
+      - name: Check secret
+        env:
+          MY_SECRET: ${{ secrets.MY_SECRET }}
+        run: |
+          if [ -n "$MY_SECRET" ]; then
+            echo "Secret is available"
+          else
+            echo "Secret is missing"
+            exit 1
+          fi
